services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app_container
    ports:
      - "8080:8080"
    volumes:
      - ./student_private.pem:/app/student_private.pem:ro
      - ./student_public.pem:/app/student_public.pem:ro
      - ./instructor_public.pem:/app/instructor_public.pem:ro
      - seed-data:/data
      - cron-output:/cron
    environment:
      - TZ=UTC
    restart: unless-stopped

volumes:
  seed-data:
  cron-output:

